apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: kube-system
  labels:
    k8s-app: logstash
spec:
  selector:
    k8s-app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044            
